import "./globals.css";
import type { Metadata } from "next";
import { inter } from "@/config/fonts";

import { getGlobal } from "@/lib/get-home";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata = {
  title: "Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const globalData = await getGlobal();
  console.dir(globalData, { depth: null });

  if (!globalData?.data?.header) {
    throw new Error("No se han recibido datos para el Header");
  }

  return (
    <html lang="en">
      <body className={`${inter.className} bg-white`}>
        <Header data={globalData.data.header} />
        {children}
        <Footer data={globalData.data.footer} />
      </body>
    </html>
  );
}
